
export NPM = $(NODEJS_NPM_BINARY)
export NODE = $(NODEJS_NODE_BINARY)
export NODE_PATH = $(NODEJS_MODULES_PATH)
export NPM_CONFIG_PREFIX = $(NODEJS_MODULES_PATH)

$(NODEJS_MODULES_PATH):
	@$(MKDIR_P) $@


